# Loading library
```{r}
library(bbmle)
```

# MLE of binomial distribution with 3 of 4 times success 
```{r}

LL <- function(pvals){
  -sum(dbinom(3,4,pvals),log=T)
}
mle2(LL,start=list(pvals=0.1))
```

# MLE of normal distribution
## MLE of muy is X_
```{r}
data = rnorm(n=1000,mean=10,sd=2)
LL <- function(mean){
  -sum(log(dnorm(data,mean=mean,sd=2)))
}
mle2(LL,start=list(mean=0.01))
```
## MLE of sigma^2 is Var(X_) -- biased
```{r}
data = rnorm(n=1000,mean=10,sd=2)
sqrt(var(data) * 1001 / 1000) # biased Var(X_)
LL <- function(sd){
  -sum(log(dnorm(data,mean=10,sd=sd)))
}
mle2(LL,start=list(sd=1))
```

##MLE of normal
```{r}
data = rnorm(n=10000,mean=10,sd=2)
LL <- function(mean,sd){
  -sum(log(suppressWarnings(dnorm(data,mean=mean,sd=sd))))
}
mle2(LL,start=list(mean=1,sd=1))
```

#MLE of bernoulli
```{r}
n = 10000
p = 0.2
data = rbinom(n,1,p)
LL <- function(p){
  -sum(log(suppressWarnings(dbinom(data,1,prob=p))))
}
mle2(LL,start=list(p=0.01))
```

#MLE of binomial
```{r}
n = 5000
p = 0.35
size = 40
data = rbinom(n,size,p)
LL <- function(p){
  -sum(log(suppressWarnings(dbinom(data,size,prob=p))))
}
sum(data) / (size*n)
mle2(LL,start=list(p=0.01))
```

#MLE of possion
```{r}
# Event happend 2 times in 25min, we interest in per 10min how many time it happend
# lamba = 10/25*2
set.seed(1234)
baseTime = 25
timesHappend = 2
interestedInInterval = 10
lambda = (interestedInInterval/baseTime)*timesHappend # Number of event happend per unit -- 10min
data = rpois(1000,lambda=lambda)
LL <- function(lambda){
  -sum(log(suppressWarnings(dpois(data,lambda=lambda))))
}
mle2(LL,start=list(lambda=1))
sum(data) / length(data)
```

# Posterior = Likelihood ( model predicted ) + Prior ( Our belief ) 
```{r}
library(manipulate)
pvals <- seq(0.01, 0.99, length = 1000)
x <- 13; n <- 20
myPlot <- function(alpha, beta){
  plot(0 : 1, 0 : 1, type = "n", xlab = "p", ylab = "", frame = FALSE)
  lines(pvals, dbeta(pvals, alpha, beta) / max(dbeta(pvals, alpha, beta)),lwd = 3, col = "darkred")
  lines(pvals, dbinom(x,n,pvals) / dbinom(x,n,x/n), lwd = 3, col = "darkblue")
  lines(pvals, dbeta(pvals, alpha+x, beta+(n-x)) / max(dbeta(pvals, alpha+x, beta+(n-x))), lwd = 3, col = "darkgreen")
  title("red=prior,green=posterior,blue=likelihood")
}
manipulate(
  myPlot(alpha, beta),
  alpha = slider(0.01, 100, initial = 1, step = .5),
  beta = slider(0.01, 100, initial = 1, step = .5)
)
```


```{r}
pvals <- seq(0.01, 0.99, length = 1000)
x <- 13; n <- 20
myPlot2 <- function(alpha, beta, cl){
  plot(pvals, dbeta(pvals, alpha+x, beta+(n-x)), type = "l", lwd = 3,
  xlab = "p", ylab = "", frame = FALSE)
  out <- binom.bayes(x, n, type = "highest",
  prior.shape1 = alpha,
  prior.shape2 = beta,
  conf.level = cl)
  p1 <- out$lower; p2 <- out$upper
  lines(c(p1, p1, p2, p2), c(0, dbeta(c(p1, p2), alpha+x, beta+(n-x)), 0),
  type = "l", lwd = 3, col = "darkred")
}
manipulate(
  myPlot2(alpha, beta, cl),
  alpha = slider(0.01, 10, initial = 1, step = .5),
  beta = slider(0.01, 10, initial = 1, step = .5),
  cl = slider(0.01, 0.99, initial = 0.95, step = .01)
)
```